### ISSUE TITLE
Some thoughts about how to integrate YAFCT in our deployment chain with roles and profiles methodology

### ISSUE THREAD

**Issue by beeva-javiermartincaro** [ITV/YAFCT#1]
Hello,

Great work in there, I was preparing a yaml template wrapper for hammer when I saw YAFCT and I think we are going to use this for our continuous deployment chain.

However, we have noticed that when used with puppet subclasses the LookUp function does not have the best performance. We use the roles and profiles workflow (http://garylarizza.com/blog/2014/02/17/puppet-workflow-part-2/), so we only assign one role per node into the hostgroup. This role has the format *role::subrole::namerole*. The problem is that the lookup function will return the most likely, which is *role* (although we specified *role::subrole::namerole*.

For example, one runlist for a HostGroup may contain:

```
---
# HOSTGROUP STACK FOR CLIENTAPI
#
# Creates the following hostgroup:
#  - project-portal
#
- "name": "@PROJECT_PORTAL@"
  "type": "HostGroup"
  "method": "update"
  "environment_id": "LookUp(Environment:@PROJECT_ENVIRONMENT_DEV@)"
  "puppetclass_ids": ["LookUp(PuppetClass:roles::project::project-portal)"]
  "puppet_ca_proxy_id" : "LookUp(Proxy:@FOREMAN_DEV@)"
  "puppet_proxy_id" : "LookUp(Proxy:@FOREMAN_DEV@)"
  "domain_id": "LookUp(Domain:@DEV_DOMAIN@)"
  "architecture_id": "LookUp(Architecture:x86_64)"
  "operatingsystem_id": "LookUp(OperatingSystem:@PROJECT_OS_DEV@)"
```

When we run the stack we found that the class asigned to the HostGroup is "roles", because of the following message: *Found more than one matching your specification... returning most likely*

We have fixed this behaviour changing a couple of lines and a simple loop, we can merge our code if you are interested.

Moreover, we have a couple of doubts about how to use the templates and de delete (destroy) method for a proper workflow. We want Jenkins to retrieve the runlists and templates from a git repository and build the entire stack into AWS, with HostGroups and Hosts, build the application, pass some tests and then destroy the entire stack.

How could we accomplish the dynamic update of the *method* parameter for a runlist? The first time Jenkins uses the stack this parameter must be *"create"*, if someone updates it must be set to *"update"* and, once all the tests are green, destroy it with *"delete"* or *"destroy"*. We are addressing this with another python script with creates the runlists dynamically, but I don't know if you are using a proper method. Another wrapper for wrap the wrapper seems like a bad method.

Another topic is the fact that, although all destroy methods are in the code, only instances can be deleted by runlists. We have changed this behaviour (as we need to destroy the hostgroups sometimes) with some if statements between the *delete_instances* method. 

Is there a reason for not delete other things than Hosts? How are you addressing this? Would you be interested in our piece of code?

The third issue we changed in our fork is that, as we have more than a hundred puppet classes, we prefer to set the page limit for searching puppetclasses to a bigger json response. We used the call as:

```
    def index_instances(self, conn):
...
        per_page = 100
...
            elif function == "PuppetClass":
                resp = conn.index_puppetclasses(per_page=per_page,page=page)
```
This change improved our performance when running large templates with multiple puppetclasses.

Sorry for the long text and all the questions, we want to thank you for the hard work. If we can help to improve this project we will be glad to do it. Would you want we to prepare a merge request with this changes?

Regards.

**Comment by s1l0uk** [comment]
Heya!

Thank you so much for the positive and constructive feedback - You are my first Issue on my very first Open Source Project! Congratulations!!

I will try and address all the issues you mentioned (I am so glad to have some feed back from other people using it!)

So the LookUp Method - the reason this is happening is because I did not think fully about the function and I am using the .split function to split on the ':' character (and greedy which is bad!) this relates to line 1588 and 1589 and needs to be changed so that it only takes the first ':' to get the resource it is altering and takes the rest as regex to search for (in my test copy I have open I have changed the split from .split(':') to .split(':',1) ).

Your next issue I believe (please correct if wrong) is that you would like to dynamically update,delete,create on the same runlist (maybe a Jenkins variable/parameter here when building with params?) - I can see what you want to do.... and I bet you don't want to keep 3 runlists up to date either ;-) - One idea that springs to mind is using the definitions.py and create a token (@METHOD@) then use sed to update the value of the token @METHOD@ from a parameter in jenkins? then when the runlist runs with the -T it will update the @METHOD@ to what Jenkins has set the variable as?? 

In runlist:
- "name": "dummy_resource"
  "type": "thing!"
  "method": @METHOD@

In definitions.py:
'@METHOD@' : "A_UNIQUE_VALUE_TO_UPDATE",

In Jenkins - The first thing the job does does:
sed -i s/A_UNIQUE_VALUE_TO_UPDATE/$JENKINS_METHOD_PARAMETER_NAME/g definitions.py

How does that sound? This way it keys nicely in to Jenkins and segregates the layers while allowing a single runlist to be used?

I love your per page - It makes so much sense!! I will be stealing this from you very soon and updating this version of YAFCT along with the first point you made! I guess again this was me just not thinking clearly and I should have thought about the potential of HUUUUUUGGGGGGEEE estates with more than X number... 

I am thinking of potentially putting this value in the config to allow you to choose? try and except keyerror and make default 100 (in your honour ;-))

Again, many thanks for your feedback on the tool :-) and please come back if you think I can be of anymore help :-)
//P

**Comment by beeva-javiermartincaro** [comment]
Thank you for your fast and clear response! This is my first opened issue in Github also, so congratulations!

I am glad we had fixed the puppet subclass in the same way. 

In the line 1613: 

```
    def lookup_element(self,conn,element):
        # split in two parts in order to see Puppet subclasses
        self.params.name = element[element.find("(")+1:element.find(")")].split(':', 1)[1]
        self.params.function = element[element.find("(")+1:element.find(")")].split(':', 1)[0]
```

And instead of the code starting in line 395, we have inserted a loop:

```
 395             if function == "PuppetClass":
 396                 temp = []
 397                 for w in resp:
 398             # Loop for extracting subclasses from name
 399                     length=len(resp[w])
 400                     if length > 1:
 401                         for i in range(length):
 402                             temp.append(resp[w][i]['puppetclass'])
 403                     else:
 404                         temp.append(resp[w][0]['puppetclass'])
 405              # End loop
```

Feel free to use it of modify this code if you think it would help.

Regarding the update from jenkins, your answer is great, we are going to use it. There is only one thing missing: could we use multiple definitions.py, or put the values to interpolate with *@value@* in other files? we want to have your project in one repository as a dependency for all our applications, and have this directory tree in another repository/repositories:

```
project1
  definitions.py (or something with the global variables PER PROJECT OR ENVIRONMENT)
  runlist
    template_hostgroups.yaml
    template_hosts.yaml
  templates
    ec2.json 
project2
  definitions.py (or something with the global variables PER PROJECT OR ENVIRONMENT)
  runlist
    template_hostgroups.yaml
    template_hosts.yaml
  templates
    ec2.json 
```

The reason for this is to place some project-dependent variables into a file and use this in the runlist templates. Makes sense, or do you have another recommendation? 

About the delete/destroy method, is there any plans for updating the code with a method to delete HostGroups? We did it with the next patch:

```
  60     # Change method to control exceptions and handle host and hostgroups
  61     def delete_instances(self,conn):
  62         hosts = self.index_instances(conn)
  63         print hosts
  64         func = self.params.function
  65         if len(hosts) == 0:
  66             quit("There are no instances that match what you are looking for.. quitting!")
  67         for host in hosts:
  68             if func == "Host":
  69                 key = 'host'
  70             elif func == "HostGroup":
  71                 key = 'hostgroup'
  72             else:
  73                 quit("Sorry, there is no delete method for this function implemented yet")
  74             host_id = host[key]['id']
  75             print host
  76             if self.params.auto != True:
  77                 resp = raw_input("\nWould you like to Delete " + key + " " + host[key]['name']  + "?: [y/n]")
  78                 if resp in ['y','ye','yes','Y','Ye','Yes','YES', 'YE']:
  79                     try:
  80                         if func == "Host":
  81                             conn.destroy_hosts(host_id)
  82                         elif func == "HostGroup":
  83                             conn.destroy_hostgroups(host_id)
  84                     except Exception, e:
  85                         self.log.error("There was an error trying to delete " + key)
  86 
  87                 else:
  88                     self.log.warn("Not operating on " + str(host_id) + " - " + host[key]['name'] )
  89                     continue
  90             else:
  91                 try:
  92                     self.destroy(conn,host_id)
  93                 except Exception, e:
  94                     self.log.error("There was an error trying to delete " + key)
```


By the way, I modified also the code for using the security groups in AWS as an array in the runlist. It is working now on AWS, in case you want to give it a try or use the code.

The template *templates/ec2.json* looks like:

```
{
    "name": "@name@",
    "organization_id": "@organization_id@",
    "root_pass": "@root_pass@",
    "comment": "@comment@",
    "compute_resource_id": "@compute_resource_id@",
    "managed": "true",
    "model_id": "",
    "provision_method": "image",
    "interfaces_attributes": {
        "new_interfaces": {
            "name": "",
            "ip": "",
            "provider": "IPMI",
            "mac": "",
            "_destroy": "false",
            "type": "Nic::Managed",
            "domain_id": ""
        }
    },
    "disk": "",
    "overwrite": "false",
    "puppet_status": 1,
    "build": "1",
    "type": "Host::Managed",
    "mac": "flavor",
    "medium_id": "@medium_id@",
    "enabled": "1",
    "hostgroup_id": "@hostgroup_id@",
    "compute_attributes": {
        "flavor_id": "@flavor@",
        "availability_zone": "",
        "subnet_id": "@subnet_id@",
        "security_group_ids": "@security_group_ids@",
        "managed_ip": "private",
        "image_id": "@ami@"
    },
    "puppetclass_ids": []
}
```

We are then creating the EC2 instance with a runlist like:

```
---
- "name": "@DEV@-@PROJECT_INSTANCE_NAME@"
  "type": "Host"
  "method": "create"
  "template": "./templates/ec2.json"
  "comment": "Creating @DEV@-@PROJECT_INSTANCE_NAME@-@DEV_DOMAIN@"
  "root_pass": ""
  "compute_resource_id": "LookUp(ComputeResource:@DEV_COMPUTE_RESOURCE@)"
  "hostgroup_id": "LookUp(HostGroup:@PROJECT_INSTANCE_ROLE@)"
  "medium_id": "1"
  "flavor": "m1.small"
  "subnet_id": "<subnet-id>"
  "security_group_ids": "<sg-id1> <sg-id2>"
  "ami": "<ami-id>"
```

The thing here is the security_group_ids. In order to use more than 1 security group into the template, we had to change the code:

```
 590         host_template = json.loads(host_template)
 591         # Security Groups as list from runlist
 592         host_template["compute_attributes"]["security_group_ids"]=host_template["compute_attributes"]["security_group_ids"].split(' ')
 593         return dict(host_template)
```

Thank you again for everything, I think this will be a killer project! :-)

**Comment by s1l0uk** [comment]
Haha! Wise minds think alike ;-)

I will look in to the PuppetClass - it seems like a good idea but I need to do a few tests with the configs here before we add it in. 

I think I understand what you are trying to do and we do similar (we have 2 sites and need to manage this), but still I only use 1 definitions file. 

To accomplish this I added extra "farms" to the config (can have same details but need different name for the -f flag) for example:
foreman:
  datacenter-project:
    
  datacenter-project2:

Now - the definitions.py - I use, what I refer to as double-barrelled tokens the idea behind it is in your 
definitions you would have:

'@DC_UPPER@' : str(self.params.farm).lower().split('-')[0], #Gives DATACENTRE
'@PROJECT_UPPER@' : str(self.params.farm).lower().split('-')[0], #Gives PROJECT1 or PROJECT2
'@PROJECT1_VARIABLE@' : 'VALUE1',
'@PROJECT2_VARIABLE@' : 'VALUE2',  

and finally in your code you have:

@@DC_UPPER@_VARIABLE@

Now when you run the tokenizer (-T) depending on which farm you are using will select the correct variables ;-) nice, light and sneaky! Although, worth noting that with YAFCT it will only tokenise the runlists. As I assumed that after foreman has provisioned, config management would take over... The sister project to YAFCT, vSPLAT uses the definitions file as well and as it uses scripts it will also tokenise the script (just a bit of history as to why I developed this way), I am not entirely sure what else would need to be able to use tokens in a foreman deploy (If you do find something - Please let me know!)

As for the delete/destroy elements - Yes! Yes Please! - I did not have time to run through it all myself ;-) and currently we are only deleting hosts so it was only required for that in our use - but please feel free to create pull requests for anything you might want to delete - Massive Thank you!

And again, Thank you for the template! That is one of the reasons I created YAFCT (after also trying to work with hammer...) I will have a detailed look at the security group stuff (I knew I would have to add extra code for different templates...) but hadn't got around to playing with AWS and Foreman yet. But I will take a look and test and most likely add in as everyone else uses AWS ;-)

Again, massive thanks for all the input - If this does become a killer project it is only thanks to people like yourself who contribute to the community - So thanks again Buddy! (My next push will not be as prompt as I am just finishing another piece of work ;-) #NotEnoughHoursInTheDay! )

**Comment by s1l0uk** [comment]
Hey again, having a quick look at the EC2 issue with security groups and I saw you are doing this:

"security_group_ids": "<sg-id1> <sg-id2>"

Would we not need the code change if it was:

"security_group_ids": ["<sg-id1>","<sg-id2>"]

As it looks like you split the string to get the list we could just feed it a list in yaml/Json? 

What do you think? It appeared to work for me :-)

Apologies if this message is unclear - I am writing from my mobile ;-)

**Comment by s1l0uk** [comment]
Haha and it removed the sg-ids from example /me facepalm

**Comment by beeva-javiermartincaro** [comment]
Hey again!

The way you put the security_group_ids was our first approach too, but there is a problem when you try to detokenize the yaml into the json. Look at the call made whith this method (I masked some values, look at the *compute_attributes* hash):

```
-------- data sent -----------------
{"host": {"comment": "Creating dev-project-domain.com", "root_pass": "", "managed": "true", "model_id": "", "provision_method": "image", "organization_id": "id", "interfaces_attributes": {"new_interfaces": {"name": "", "ip": "", "provider": "IPMI", "mac": "flavor", "_destroy": "false", "type": "Nic::Managed", "domain_id": ""}}, "mac": "flavor", "disk": "", "overwrite": "false", "compute_resource_id": 1, "name": "dev-project-002", "medium_id": "1", "enabled": "1", "hostgroup_id": 74, "compute_attributes": {"security_group_ids": "['sg-1', 'sg-2']", "availability_zone": "", "subnet_id": "subnet", "image_id": "ami", "flavor_id": "m1.small", "managed_ip": "private"}, "build": "1", "puppetclass_ids": [], "type": "Host::Managed", "puppet_status": 1}}

```

The thing here is that security_groups_ids is inside a hash and an extra quotes are placed. so instead of *"security_group_ids": "['sg-1', 'sg-2']"* it should be *"security_group_ids": ["sg-1", "sg-2"]* (last is the correct api call).

My way was a quick (and dirty, I know that) response in order to make this work, but if you know how to do it better it would be great :-)

About the farms, we have three Foreman instances inside our organization, each with several projects from different clients. The thing we are trying to solve is that data relative to one client should not be shared with another. That is the reason we want to separate the core of YAFCT (the code for provisioning things) from the config (runlist, templates and definitions.py. Maybe even config.yaml). 

We can manage different packages with the whole YAFCT code, but an update becomes a nightmare when you need to do it in different places at the same time. That was the thing we were trying to avoid when we planned our new alternative to Hammer which, by the way, we called Nails (Not Another Infrastructure Launcher Script) :-D

I will prepare a pull request with another minor changes I made to the core, if you want to refactor or change what I did, please feel free.

Regards!

**Comment by s1l0uk** [comment]
Aha! I see - When the template is loaded in it is only loaded in as text with a .read() - Did you still have the quotation marks in the template still? as it does a find and replace while reading so you would have ended up with "[item1,item2]" instead of [item1,item2]

Can you try the template like this:

"security_group_ids": @security_group_ids@,

This should allow the list to populate without casting it as a string - although technically breaks the laws of JSON...

I like your thinking behind the change of definitions - my problem at the moment is that it gets imported and I haven't found a nice way to flip the definitions within the script (maybe use importlib) library and use a param... In the mean time before I come up with a nicer way of dealing with the problem natively would it be worth using soft links? linking the projects definitions file to definitions.py then the script would use whatever is set?

Let me know how you get on... I will hopefully have some time tonight to have a play and try and get some more features pushed in!

Thanks,
//P

**Comment by beeva-javiermartincaro** [comment]
We tried that already. Unfortunately, as you said, the JSON laws prevent you for doing this. 

```
Traceback (most recent call last):
  File "./foremanTool.py", line 1677, in <module>
    foremanTool.run()
  File "/usr/local/lib/python2.7/dist-packages/cli/app.py", line 245, in run
    return self.post_run(returned)
  File "/usr/local/lib/python2.7/dist-packages/cli/app.py", line 241, in run
    returned = self.main(*args)
  File "./foremanTool.py", line 1650, in main
    self.deploy_runlist(connection)
  File "./foremanTool.py", line 551, in deploy_runlist
    self.log.error(self.create(conn,element))
  File "./foremanTool.py", line 585, in create
    element = self.compile_host_template(element)
  File "./foremanTool.py", line 578, in compile_host_template
    host_template = json.loads(host_template)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
That is the reason I ended with the rough solution of separating the hash with spaces.

I like the definitions soft links, I am going to try to automate it. Thank you for the tip!

**Comment by beeva-javiermartincaro** [comment]
Hey there!!

I was thinking again about the multiple definitions.py files (in order to separate project data from definitions when we build different projects) and I made up a simple solution using the extra JSON params. 

In definitions.py:

```
#!/usr/bin/env python

import json

def definitions(self):
    definitions = {
        '@SOMEDEFS@' : "SOMEVALUES",
    }

    # The new code for appending or write some new defs: 

    if self.params.extra:
        extra_data = json.loads(self.params.extra)
        definitions.update(extra_data)
    return definitions

```

This will dynamically use a different dict object when you change the -e "$(cat ./path/to/json)" flag in the YAFCT call (we think Jenkins could build different jobs with different definitions.py in parallel).

It makes sense, or do you think it could break something?

Thank you for your help!

**Comment by s1l0uk** [comment]
Hey Buddy! 

Sorry for the delay in the reply - I haven't forgotten you, I just wanted to put code to repo before getting back.
 
Sooo a quick overview of what I have been up to:

PuppetClasses - I have been playing with your loop and really like it! So going to add in on my next commit

The python "list" issue in JSON - Again, I wasn't too sure about playing with the code too much on this (scared of creating an endless list of 'if host[x] - do X') to suit everyone - I believe I have got to the root of the issue (and found the code I lost that prevented that error) in compile_host_template function:
   
We load the template in as text (.read()) and do a basic find and replace - What was happening under the hood (when you had a list in the YAML and no quotes in the template field) was the template was being populated with ['sg-123456','sg-654321'] the use of ' is illegal in json (except if it's in a string(?), which I can't see being transposed to the data handled by YAFCT). to remedy this I added an extra .replace("'",'"') (single quote, double quote, single quote, comma, double quote, single quote, double quote) and now ALL lists dropped into place will load.

The multiple definitions.py - I think you have done it!!! I just tried it out on Python CLI and... 

OMG!! you can do that in Python???!!! I love this language! 

I was playing around with the idea of using the load module from string (I do not like it..). I think your way is much cleaner and to be honest... a "game-changer" as I am looking at the script totally differently now.  The only thing I would like to change is to use another parameter (as it breaks YAFCT's sister script...) to deal with it - Then you could make a list of all the extra definitions and get better granulation for your environment and fleet types - what do you think?

**Comment by beeva-javiermartincaro** [comment]
As almost everything in this issue is resolved now I think we can close it and start another thread if required. :-)

This is being so helpful, thank you so much for all the support!

**Comment by s1l0uk** [comment]
Hey Buddy!

Totally agree - Thank you again for your input towards this, hopefully your deployment life is a lot easier now. If you need any more advice or have any more features. Please get back in contact!

Thanks,
//P

**Comment by beeva-javiermartincaro** [comment]
Thank you, we will be in touch with new updates as soon as we improve our devops chain!
